### ISSUE TITLE
dead code is better to be removed

### ISSUE THREAD

**Issue by kostas-kapasakis** [reef-defi/reef-client#304]
https://github.com/reef-defi/reef-client/blob/b2d59464453d0e8b64fb2b0d2d99c880f5418f89/src/app/app.component.ts#L64-L72

**Comment by filipbarak** [comment]
Hello Kostas,

We're aware of the commented out code, but since it's not affecting the application runtime in any way, we will be removing it in later iterations.

Thanks for the concern.
